### ISSUE TITLE
7900XTX

### ISSUE THREAD

**Issue by Rav8es** [CatWithCode/catwithcode.github.io#1]
I love Pop!_OS. I didn't have luck with your Blog post guide for using Pop!_OS with 7900 XTX.

Maybe I missed something...

sudo add-apt-repository ppa:kisak/kisak-mesa

sudo apt update

sudo apt upgrade

#

sudo gedit /etc/apt/preferences.d/kisak-pin-2000
Package: *
Pin: release o=LP-PPA-kisak-kisak-mesa
Pin-Priority: 2000

#

sudo apt update

sudo apt upgrade

#

git clone  https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
cd linux-firmware/
sudo mv /lib/firmware/amdgpu /lib/firmware/amdgpu_backup
sudo cp -r amdgpu /lib/firmware/
sudo Dracut -f

**Comment by CatWithCode** [comment]
i think you forgot the following step: "Now we need to force Pop OS to use the new Repository for MESA.". Without this step apt will ignore the new MESA version. 

Also you should COPY not move your firmware files outside of the lib folder. something like home for example: sudo cp /lib/firmware/amdgpu /home/YOUR_NAME/amdgpu_backup. 

And you theme to have forgoten the last 2 steps with "The only thing missing now is to rebuild the initframfs. After that, the Kernel should recognize the GPU:" (initframfs) and enabling wayland "I highlight recommend using WAYLAND! XORG is really buggy with this Setup (Crashes and invisible Curser) but WAYLAND works near perfectly (As perfect as Wayland can work):". Hope i could help. :)

**Comment by Rav8es** [comment]
That worked. 

I have cursor working in X11

sudo nano /etc/X11/xorg.conf.d/20-amdgpu.conf

Section “Device”
       Identifier “AMD”
       Driver “amdgpu”
       Option “SWCursor” “True”
End Section


Side note… DP output does not work for me on either port. Must use HDMI.

**Comment by CatWithCode** [comment]
I did not have the DP-Issue.
Can not test it anymore. Switched to Arch because the newest Update supports the Hardware now.
I added a Link to your X11 fix! Thx!

**Comment by Rav8es** [comment]
I found Manjaro boots, but doesn’t seem to recognize the GPU. Can’t launch Vulkan games.

**Comment by CatWithCode** [comment]
I don' like Manjaro. Can not really comment on there modifications.

**Comment by Rav8es** [comment]
As of now, I don't think there is a single distro that supports the 7900 XT / XTX. 

Manjaro boots, but you are booting in with llvmpipe. (Can't find GPU in AMDGPU). You can install Mesa-Git, along with lib32-mesa-git, and any vulkan utils you want.

Many Vulkan games are broken with dev level mesa. It's a mess honestly.

Pop OS is my favorite out of box, but ever since I updated to AM5, Vulkan games run horribly on their distro.

**Comment by Mondrethos** [comment]
> I did not have the DP-Issue.
> 
> Can not test it anymore. Switched to Arch because the newest Update supports the Hardware now.
> 
> I added a Link to your X11 fix! Thx!

How are you getting it to work on Arch? RDNA3 requires llvm15 at the minimum and the only one in the repo is 14. The only way I got Arch to work was to use the unofficial mesa/git from the wiki which comes with llvm16 as mentioned in the arch and endeavouros.

It has not been just update and go for me.

**Comment by CatWithCode** [comment]
I connected my display to the motherboard, started the arch iso, installed it with "archinstall", booted it up one time, shutdown the system and connected the display to the GPU, booted back up and everything works perfectly. I used the 12.2022 ISO of arch. I don't know why it dose not work for you... for me it works perfectly after installing it like this.

**Comment by kprinssu** [comment]
A quick addition to the fun of new hardware, I keep getting frequent hangs with the latest mesa drivers. The issue is raised is with the [Gitlab project](https://gitlab.freedesktop.org/drm/amd/-/issues/1974), but currently there is no proper fix. 


The workaround that works for me is to set the card to high performance mode but this sucks a lot of power at idle.  I created a new service that sets the card to high performance mode by doing the following:

1. Creating a new service at `/etc/systemd/system/gpu-power.service` with the following contents:
```
[Unit]
Description = "Set the GPU PowerScaling to high"

[Service]
ExecStart=/usr/bin/sh -c 'echo "high" > /sys/class/drm/card0/device/power_dpm_force_performance_level'
Type=idle

[Install]
WantedBy=multi-user.target
```

2. Enable it via `sudo systemctl enable gpu-power.service`
3. Restart my computer
4. Verify the card is in high performance mode by doing `cat /sys/class/drm/card0/device/power_dpm_force_performance_level`. The output should be `high`.

**Comment by Mondrethos** [comment]
> A quick addition to the fun of new hardware, I keep getting frequent hangs with the latest mesa drivers. The issue is raised is with the [Gitlab project](https://gitlab.freedesktop.org/drm/amd/-/issues/1974), but currently there is no proper fix.
> 
> The workaround that works for me is to set the card to high performance mode but this sucks a lot of power at idle. I created a new service that sets the card to high performance mode by doing the following:
> 
>     1. Creating a new service at `/etc/systemd/system/gpu-power.service` with the following contents:
> 
> 
> ```
> [Unit]
> Description = "Set the GPU PowerScaling to high"
> 
> [Service]
> ExecStart=/usr/bin/sh -c 'echo "high" > /sys/class/drm/card0/device/power_dpm_force_performance_level'
> Type=idle
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
>     2. Enable it via `sudo systemctl enable gpu-power.service`
> 
>     3. Restart my computer
> 
>     4. Verify the card is in high performance mode by doing `cat /sys/class/drm/card0/device/power_dpm_force_performance_level`. The output should be `high`.
> 
> 
> Just a big heads up, Pop_Os! has 22.2+ mesa drivers in the latest set of packages!

I get this every so often on my 7900 XT in the middle of games, but it's really random, can go a whole day without one and then bam. I've gone ahead and done this, and I see the output as high, so will report back how it functions.

Does this kind of stuff eventually get fixed? Never had an AMD card before.

**Comment by CatWithCode** [comment]
I never had a AMD-GPU before either. Had always Nivida before. And i also never had such bleeding edge new hardware. Can not really comment on that. But as far as i can see, mesa is relatively well maintained and updated software (in comparison to Nvidia).

**Comment by kprinssu** [comment]
@Mondrethos Considering it's a very problematic issue and seems pretty widespread with RDNA 3, I sure hope so.

**Comment by Rav8es** [comment]
You’re on Linux. Anything bleeding edge takes around 2 months to arrive on distros which give newer kernel options and dev Mesa.

**Comment by CatWithCode** [comment]
I noticed it only works if the integrated gpu of my cpu is enabled in the BIOS. as soon as i disable it everthing becomes extremely broken and glitchy in Gnome.  I get the full performance of  my 7900xt in both cases. It is only really stable with integrated gpu enabled in the BIOS.

**Comment by CatWithCode** [comment]
I have the feeling it is actually still broken in the background but the integrated gpu is piping it through it self which fixes it or something. I really don't know! Some games show me stuff like this (FF14_Online). I can render it on one of 3 screens each time with one of two gpu
![grafik](https://user-images.githubusercontent.com/56090976/211166062-b4691b49-7eaf-4579-9dd3-2afdbb0df1bf.png)

**Comment by Mondrethos** [comment]
> I have the feeling it is actually still broken in the background but the integrated gpu is piping it through it self which fixes it or something. I really don't know! Some games show me stuff like this (FF14_Online). I can render it on one of 3 screens each time with one of two gpu
> 
> ![grafik](https://user-images.githubusercontent.com/56090976/211166062-b4691b49-7eaf-4579-9dd3-2afdbb0df1bf.png)
> 
> 

Are you in Arch? Arch does not have out of the box support. Only the iGPU works. You have to use the unofficial mesa repo like was mentioned above. The only distorts to have card support are Ubuntu/popos doing the steps in your guide or fedora. Fedora (what I switched to from arch) in the mean time works out of the box indeed you update. I've been playing FFXIV just fine for days and it seems like the hang up went away after it happened once more with the edit above about the power management setting.

**Comment by Mondrethos** [comment]
> @Mondrethos Considering it's a very problematic issue and seems pretty widespread with RDNA 3, I sure hope so.

Is it still happening to you? Happens to me every so often but we haven't really ahd a major mesa update since the cards came out.

**Comment by Mondrethos** [comment]
> I still have the issue, it looks to me that Firefox is consistently causing these hangs for me. Mesa 23.0 is currently underway to be released as it just hit release candidate status.
> 
> 
> 
> However, I am using the bleeding edge builds of it and I still do often get hangs.

I switched Firefox off hardware rendering and that really helped. I might sometimes get a hang in FFXIV and sometimes consistently. I'm hoping 23.0 helps but if it hasn't for you, that's not promising.

**Comment by Mondrethos** [comment]
> In regards to the hangs, are you using X11 or Wayland. The only hangs I experienced are under Wayland. 
> 
> 
> 
> I have had way more success with distros other than Pop. Pop is too customized to be playing around with Mesa PPAs and bleeding edge stuff in my opinion. Try kubuntu, Ubuntu, Ubuntu flavors, or fedora. After all, kisak and oibaf PPAs are designed around Ubuntu and Ubuntu flavors. 
> 
> 
> 
> Personally I’m using kubuntu with X11, and have yet to experience any issues while using kisak PPA and Ubuntu mainline PPA using the latest RC. 

Wayland Fedora currently. Fedora has the proper llvm version required out of the box. I'm not near my computer right now but I think it's mesa 22.3 and the kernel is up there as well.

I'd have to figure out how to change to mesa RC. This is my first amd card ever and I've never had had to do anything but use nvidia drivers.

Been using gnome as my prefered desktop but I've been looking at kde for a bit and kubuntu. Unless you are using the tips here in this blog. I did that for popos, switching to the ppa and that hung as well.

**Comment by Rav8es** [comment]
I use X11. 

Need to enable SW cursor as mentioned above. Try that and see if you have the same results.

**Comment by Mondrethos** [comment]
> I use X11. 
> 
> 
> 
> Need to enable SW cursor as mentioned above. Try that and see if you have the same results. 
> 
> 
> 
> Ubuntu or KDE is the same as the tips in the blog except no need to use pin priorities for PPA. You install PPA. Ubuntu Mainline PPA gives you the ability to chose kernel, even RC, no need to stick to Pop custom kernel. 

Will try that. Do you game any?

Do you recommend I update to an ex version of mesa?

**Comment by kprinssu** [comment]
I don't play a lot of games nowadays. Mostly, developer work and productivity work. 

In regards to which mesa version, honestly, it's been a crap chute. There are numerous issues created with the blame being shifted between the kernel and amdgpu drivers. 

Fortunately,  I think they will fix this soon (tm), as few of the amdgpu developers have [gotten their hands](https://gitlab.freedesktop.org/mesa/mesa/-/issues/7939#note_1725170) on the new RDNA 3 cards. I am just an enthusiast and probably going back to my Macbook for the time being until I get my replacement card from AMD.

**Comment by Mondrethos** [comment]
> > > I use X11.
> > > Need to enable SW cursor as mentioned above. Try that and see if you have the same results.
> > > Ubuntu or KDE is the same as the tips in the blog except no need to use pin priorities for PPA. You install PPA. Ubuntu Mainline PPA gives you the ability to chose kernel, even RC, no need to stick to Pop custom kernel.
> > 
> > 
> > Will try that. Do you game any?
> > Do you recommend I update to an ex version of mesa?
> 
> I’m using kisak ppa. Kisak is safer in my opinion with the 7900 XTX at least. I’m looking for early releases and llvm15.
> 
> Oibaf may be a little risky I haven’t tried with the 7900 XTX. Oibaf is DEV similar to Mesa git on Arch.
> 
> I game using Steam. You may run into problems using Lutris as I bet most of their games are using llvm14 in the installer.
> 
> Steam for Linux is officially supported on Ubuntu and Ubuntu flavors only. Example, if I install git Mesa and all adds in Manjaro, most steam games using vulkan are broken with 7900 XTX. I have not run into these issues on Ubuntu. This is why Mike V on phoronix is using Ubuntu to test bleeding edge hardware.
> 
> Pop is not a Ubuntu flavor. It’s based on Ubuntu, but highly customized. Example, my AM5 platform 7950X and 7900 XTX runs poorly on Pop in gaming. When using Ubuntu/flavors or Manjaro, it runs perfect as good or better than Windows. Pop has gone too customized, and has led to problems for me. These same problems exist if I use a 6950XT on a AM5 platform. If I switch to AM4, the problems disappear.
> 
> Also keep in mind, AMD releases their firmware to Ubuntu and Fedora only.

Am on X with SW cursor to see if it hangs. However, SW Cursor flickers like crazy when it decides to go bonkers, any idea on that?

**Comment by JMLX42** [comment]
Thank you for the great article!

AFAIK my (e)GPU (7900 XTX) is now detected and used by Wayland.

```
ame of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context, 
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_framebuffer_sRGB, GLX_ARB_multisample, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_get_drawable_type, GLX_EXT_libglvnd, GLX_EXT_no_config_context, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_MESA_copy_sub_buffer, GLX_OML_swap_method, GLX_SGIS_multisample, 
    GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, GLX_SGIX_visual_select_group, 
    GLX_SGI_make_current_read
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
client glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context, 
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_framebuffer_sRGB, GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_ATI_pixel_format_float, GLX_EXT_buffer_age, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_no_config_context, GLX_EXT_swap_control, 
    GLX_EXT_swap_control_tear, GLX_EXT_texture_from_pixmap, 
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_INTEL_swap_event, 
    GLX_MESA_copy_sub_buffer, GLX_MESA_query_renderer, GLX_MESA_swap_control, 
    GLX_NV_float_buffer, GLX_OML_swap_method, GLX_OML_sync_control, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control, GLX_SGI_video_sync
GLX version: 1.4
GLX extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context, 
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_framebuffer_sRGB, GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_buffer_age, GLX_EXT_create_context_es2_profile, 
    GLX_EXT_create_context_es_profile, GLX_EXT_fbconfig_packed_float, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_no_config_context, GLX_EXT_swap_control, 
    GLX_EXT_swap_control_tear, GLX_EXT_texture_from_pixmap, 
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_MESA_copy_sub_buffer, 
    GLX_MESA_query_renderer, GLX_MESA_swap_control, GLX_OML_swap_method, 
    GLX_OML_sync_control, GLX_SGIS_multisample, GLX_SGIX_fbconfig, 
    GLX_SGIX_pbuffer, GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_video_sync
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD Radeon RX 7900 XTX (gfx1100, LLVM 15.0.5, DRM 3.49, 6.1.7-060107-generic) (0x744c)
    Version: 23.1.0
    Accelerated: yes
    Video memory: 24576MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
```

But chromium does not use hardware acceleration:

![image](https://user-images.githubusercontent.com/998703/213430945-b3afa80a-f477-44d0-aa6d-0f342ef22ac9.png)

**Comment by CatWithCode** [comment]
Same in Firefox?

**Comment by JMLX42** [comment]
> If I use a Chromium build from https://download-chromium.appspot.com/ then the GPU is detected and working:

The same with Firefox: if I run `firefox` directly from the build downloaded from firefox.com then hardware acceleration is working.

**Comment by CatWithCode** [comment]
Repo or Flatpack?

**Comment by JMLX42** [comment]
> Repo or Flatpack?

I installed Firefox via the mozilla PPA. And hardware acceleration is OK.

**Comment by CatWithCode** [comment]
Flatpacks sometimes have outdated librarys which cause such issues. in such cases you should install native pgk's

**Comment by Rav8es** [comment]
The newest version of Manjaro is loaded with llvm 15+ and kernel 6.1+. 7900 XTX / XT is detected and works native out of box. Must still do cursor fix on X11 for proper KDE support.

**Comment by Rav8es** [comment]
Flickering removed from X11 by adding:

Option "TearFree" "true"

**Comment by Rav8es** [comment]
Pop OS has released updated Mesa using llvm15 and a new Kernel for testing

sudo apt-manage add popdev:mesa-22.3.4

sudo apt-manage add popdev:linux-6.1.6

Still have to inject firmware. Firmware was updated recently. Kisak ppa no longer needed.

**Comment by Mondrethos** [comment]
I wonder if FFVIX hangs still happen.

**Comment by CatWithCode** [comment]
Tested. For me it still dose not happen. But i never encountered this issue.

**Comment by Mondrethos** [comment]
You got a lvl 90 and caught up with the story?

Enter The Fell Court of Troia dungeon and get all the way to the final boss. The crash happens there, if you can complete the dungeon or not please let us know.

**Comment by CatWithCode** [comment]
Only lvl 65 xD sorry not that far in the game. :S

**Comment by kprinssu** [comment]
Heads up, mesa-git (main/master branch) contains a lot of fixes for the random GPU hangs and resets. I have not had a random hang with my 7900 XTX for the last few days.

We now have to wait for the fixes to be backported to 22.2.x and 22.3.x and 23.x :).

**Comment by Mondrethos** [comment]
> Heads up, mesa-git (main/master branch) contains a lot of fixes for the random GPU hangs and resets. I have not had a random hang with my 7900 XTX for the last few days.
> 
> 
> 
> We now have to wait for the fixes to be backported to 22.2.x and 22.3.x and 23.x :).

Yup!

Been playing on Mesa-hit. Not a single hang from ffxiv or Firefox or anything. I am so happy lol.

**Comment by CatWithCode** [comment]
After a lot of playing since getting it working, i notices certain actions cause a driver reset (Gnome or WAYFIRE just crashes back to login, but keeps software open inaccessible). Hope this fixes this to. It is rare and reproducible (Drag and drooping a Firefox-Tab really fast or one level in a game while ALT+TAB).

**Comment by jerzywilczek** [comment]
I think pop ships the new firmware now, no need to inject manually

**Comment by jerzywilczek** [comment]
and, as of now, mesa 22.3.4. I removed the kisak ppa and it works on wayland.
