### ISSUE TITLE
x670 bios

### ISSUE THREAD

**Issue by NickHumphries** [CatWithCode/catwithcode.github.io#4]
Hi Again Cat,

After my last post, where I listed the ee.gigabyte website, I found that the UK web site had the f4c bios, dated 2023-01-17
https://www.gigabyte.com/Motherboard/X670-GAMING-X-AX-rev-10/support#support-dl-bios

So, I'm using that one for now. Not sure why the one you found isn't there, perhaps it will turn up later.
So far, so good!

Cheers,

Nick.

**Comment by CatWithCode** [comment]
I linked the removed f4d bios on my entry. it is still online just not visible.
